version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:15-alpine # 使用轻量级的Postgres镜像
    container_name: smartdorm-db
    environment:
      POSTGRES_USER: user        # 与 application.yml 中配置一致
      POSTGRES_PASSWORD: password  # 与 application.yml 中配置一致
      POSTGRES_DB: smart_dorm    # 与 application.yml 中配置一致
    ports:
      - "5432:5432" # 将容器的5432端口映射到主机的5432端口
    volumes:
      - pgdata:/var/lib/postgresql/data # 数据持久化，防止容器重启后数据丢失

volumes:
  pgdata: # 定义一个数据卷